### ISSUE TITLE
Manual Adding data to ORKG

### ISSUE THREAD

**Issue by eacikgoe** [BeneSell/DIS18a-b-Group-4#4]
We are more confident to add the data manually in ORKG.  We should do this first to get familiar with ORKG.

**Comment by saksel1** [comment]
Data has been uploaded manually in ORKG on 7th June 23. https://orkg.org/u/596a484f-1d89-4bce-84aa-4142523f3802/papers

<img width="844" alt="image" src="https://github.com/BeneSell/DIS18a-b-Group-4/assets/115710574/d92c41e7-6131-4227-bd6c-381a2a859719">
